version: 2
updates: 
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: npm
  directory: "/"
  open-pull-requests-limit: 50
  schedule: 
    interval: "daily"
    time: "08:00"
    timezone: "Asia/Tokyo"